// ===== Countries & Cities Data =====
// Used to populate the location dropdowns in Options

export const COUNTRIES = [
  {
    code: "SA",
    name: "Saudi Arabia",
    ar: "المملكة العربية السعودية",
    cities: [
      "Riyadh",
      "Makkah",
      "Madinah",
      "Jeddah",
      "Dammam",
      "Khobar",
      "Abha",
      "Tabuk",
      "Hail",
      "Jizan",
      "Najran",
      "Buraidah",
      "Khamis Mushait",
    ],
  },
  {
    code: "EG",
    name: "Egypt",
    ar: "مصر",
    cities: [
      "Cairo",
      "Alexandria",
      "Giza",
      "Port Said",
      "Suez",
      "Luxor",
      "Aswan",
      "Tanta",
      "Mansoura",
      "Ismailia",
      "Fayyum",
      "Zagazig",
      "Damanhur",
    ],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    ar: "الإمارات العربية المتحدة",
    cities: [
      "Dubai",
      "Abu Dhabi",
      "Sharjah",
      "Al Ain",
      "Ajman",
      "Ras Al Khaimah",
      "Fujairah",
      "Umm Al Quwain",
    ],
  },
  {
    code: "MA",
    name: "Morocco",
    ar: "المغرب",
    cities: [
      "Casablanca",
      "Rabat",
      "Fes",
      "Marrakech",
      "Tangier",
      "Agadir",
      "Meknes",
      "Oujda",
      "Kenitra",
      "Tetouan",
      "Safi",
    ],
  },
  {
    code: "DZ",
    name: "Algeria",
    ar: "الجزائر",
    cities: [
      "Algiers",
      "Oran",
      "Constantine",
      "Annaba",
      "Blida",
      "Batna",
      "Djelfa",
      "Sétif",
      "Sidi Bel Abbès",
      "Biskra",
      "Bejaia",
    ],
  },
  {
    code: "IQ",
    name: "Iraq",
    ar: "العراق",
    cities: [
      "Baghdad",
      "Basra",
      "Mosul",
      "Erbil",
      "Kirkuk",
      "Najaf",
      "Karbala",
      "Nasiriyah",
      "Amarah",
      "Samarra",
      "Fallujah",
    ],
  },
  {
    code: "SD",
    name: "Sudan",
    ar: "السودان",
    cities: [
      "Khartoum",
      "Omdurman",
      "Port Sudan",
      "Kassala",
      "El Obeid",
      "Kosti",
      "Wad Medani",
      "El Fasher",
      "Nyala",
    ],
  },
  {
    code: "YE",
    name: "Yemen",
    ar: "اليمن",
    cities: [
      "Sana'a",
      "Aden",
      "Taiz",
      "Al Hudaydah",
      "Ibb",
      "Mukalla",
      "Dhamar",
    ],
  },
  {
    code: "SY",
    name: "Syria",
    ar: "سوريا",
    cities: [
      "Damascus",
      "Aleppo",
      "Homs",
      "Latakia",
      "Hama",
      "Raqqa",
      "Deir ez-Zor",
      "Tartus",
      "Idlib",
    ],
  },
  {
    code: "TN",
    name: "Tunisia",
    ar: "تونس",
    cities: [
      "Tunis",
      "Sfax",
      "Sousse",
      "Kairouan",
      "Bizerte",
      "Gabès",
      "Ariana",
      "Gafsa",
      "Monastir",
      "Nabeul",
    ],
  },
  {
    code: "JO",
    name: "Jordan",
    ar: "الأردن",
    cities: [
      "Amman",
      "Zarqa",
      "Irbid",
      "Aqaba",
      "Salt",
      "Madaba",
      "Mafraq",
      "Jerash",
      "Karak",
      "Tafilah",
    ],
  },
  {
    code: "KW",
    name: "Kuwait",
    ar: "الكويت",
    cities: [
      "Kuwait City",
      "Al Ahmadi",
      "Hawalli",
      "Al Farwaniyah",
      "Al Jahra",
      "Mubarak Al-Kabeer",
    ],
  },
  {
    code: "QA",
    name: "Qatar",
    ar: "قطر",
    cities: [
      "Doha",
      "Al Rayyan",
      "Al Wakrah",
      "Al Khor",
      "Umm Salal",
      "Al Daayen",
    ],
  },
  {
    code: "BH",
    name: "Bahrain",
    ar: "البحرين",
    cities: [
      "Manama",
      "Riffa",
      "Muharraq",
      "Hamad Town",
      "A'ali",
      "Isa Town",
      "Sitra",
    ],
  },
  {
    code: "OM",
    name: "Oman",
    ar: "سلطنة عمان",
    cities: [
      "Muscat",
      "Seeb",
      "Salalah",
      "Barka",
      "Sohar",
      "Ibri",
      "Nizwa",
      "Sur",
      "Rustaq",
    ],
  },
  {
    code: "LB",
    name: "Lebanon",
    ar: "لبنان",
    cities: [
      "Beirut",
      "Tripoli",
      "Sidon",
      "Tyre",
      "Zahle",
      "Jounieh",
      "Baalbek",
      "Nabatieh",
      "Byblos",
    ],
  },
  {
    code: "LY",
    name: "Libya",
    ar: "ليبيا",
    cities: [
      "Tripoli",
      "Benghazi",
      "Misrata",
      "Bayda",
      "Zawiya",
      "Tobruk",
      "Sabha",
      "Khoms",
      "Zliten",
    ],
  },
  {
    code: "PS",
    name: "Palestine",
    ar: "فلسطين",
    cities: [
      "Jerusalem",
      "Gaza City",
      "Hebron",
      "Nablus",
      "Ramallah",
      "Jenin",
      "Khan Yunis",
      "Bethlehem",
      "Tulkarm",
      "Rafah",
    ],
  },
  {
    code: "TR",
    name: "Turkey",
    ar: "تركيا",
    cities: [
      "Istanbul",
      "Ankara",
      "Izmir",
      "Bursa",
      "Adana",
      "Gaziantep",
      "Antalya",
      "Konya",
      "Kayseri",
      "Mersin",
      "Diyarbakir",
    ],
  },
  {
    code: "PK",
    name: "Pakistan",
    ar: "باكستان",
    cities: [
      "Karachi",
      "Lahore",
      "Faisalabad",
      "Rawalpindi",
      "Islamabad",
      "Multan",
      "Peshawar",
      "Quetta",
      "Sialkot",
      "Hyderabad",
    ],
  },
  {
    code: "BD",
    name: "Bangladesh",
    ar: "بنغلاديش",
    cities: [
      "Dhaka",
      "Chittagong",
      "Khulna",
      "Rajshahi",
      "Sylhet",
      "Barisal",
      "Rangpur",
      "Comilla",
    ],
  },
  {
    code: "ID",
    name: "Indonesia",
    ar: "إندونيسيا",
    cities: [
      "Jakarta",
      "Surabaya",
      "Bandung",
      "Medan",
      "Semarang",
      "Makassar",
      "Palembang",
      "Depok",
      "Tangerang",
      "Yogyakarta",
    ],
  },
  {
    code: "MY",
    name: "Malaysia",
    ar: "ماليزيا",
    cities: [
      "Kuala Lumpur",
      "George Town",
      "Ipoh",
      "Shah Alam",
      "Johor Bahru",
      "Malacca City",
      "Kota Kinabalu",
      "Kuching",
    ],
  },
  {
    code: "IN",
    name: "India",
    ar: "الهند",
    cities: [
      "New Delhi",
      "Mumbai",
      "Hyderabad",
      "Chennai",
      "Kolkata",
      "Bangalore",
      "Ahmedabad",
      "Lucknow",
      "Bhopal",
      "Patna",
    ],
  },
  {
    code: "US",
    name: "United States",
    ar: "الولايات المتحدة",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Jacksonville",
      "Detroit",
      "Memphis",
      "Dearborn",
    ],
  },
  {
    code: "GB",
    name: "United Kingdom",
    ar: "المملكة المتحدة",
    cities: [
      "London",
      "Birmingham",
      "Manchester",
      "Glasgow",
      "Liverpool",
      "Leeds",
      "Sheffield",
      "Edinburgh",
      "Bristol",
      "Leicester",
      "Bradford",
    ],
  },
  {
    code: "FR",
    name: "France",
    ar: "فرنسا",
    cities: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
    ],
  },
  {
    code: "DE",
    name: "Germany",
    ar: "ألمانيا",
    cities: [
      "Berlin",
      "Hamburg",
      "Munich",
      "Cologne",
      "Frankfurt",
      "Stuttgart",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Bremen",
    ],
  },
  {
    code: "CA",
    name: "Canada",
    ar: "كندا",
    cities: [
      "Toronto",
      "Montreal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
      "Quebec City",
      "Hamilton",
      "Mississauga",
    ],
  },
  {
    code: "AU",
    name: "Australia",
    ar: "أستراليا",
    cities: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Canberra",
      "Newcastle",
      "Geelong",
    ],
  },
  {
    code: "NL",
    name: "Netherlands",
    ar: "هولندا",
    cities: [
      "Amsterdam",
      "Rotterdam",
      "The Hague",
      "Utrecht",
      "Eindhoven",
      "Tilburg",
    ],
  },
  {
    code: "BE",
    name: "Belgium",
    ar: "بلجيكا",
    cities: [
      "Brussels",
      "Antwerp",
      "Ghent",
      "Charleroi",
      "Liège",
      "Bruges",
      "Namur",
    ],
  },
  {
    code: "SE",
    name: "Sweden",
    ar: "السويد",
    cities: [
      "Stockholm",
      "Gothenburg",
      "Malmö",
      "Uppsala",
      "Västerås",
      "Örebro",
    ],
  },
  {
    code: "NO",
    name: "Norway",
    ar: "النرويج",
    cities: [
      "Oslo",
      "Bergen",
      "Trondheim",
      "Stavanger",
      "Drammen",
      "Fredrikstad",
    ],
  },
  {
    code: "DK",
    name: "Denmark",
    ar: "الدنمارك",
    cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  },
  {
    code: "FI",
    name: "Finland",
    ar: "فنلندا",
    cities: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku"],
  },
  {
    code: "CH",
    name: "Switzerland",
    ar: "سويسرا",
    cities: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne"],
  },
  {
    code: "AT",
    name: "Austria",
    ar: "النمسا",
    cities: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  },
  {
    code: "IT",
    name: "Italy",
    ar: "إيطاليا",
    cities: [
      "Rome",
      "Milan",
      "Naples",
      "Turin",
      "Palermo",
      "Genoa",
      "Bologna",
      "Florence",
    ],
  },
  {
    code: "ES",
    name: "Spain",
    ar: "إسبانيا",
    cities: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Seville",
      "Zaragoza",
      "Málaga",
      "Ceuta",
      "Melilla",
    ],
  },
  {
    code: "RU",
    name: "Russia",
    ar: "روسيا",
    cities: [
      "Moscow",
      "Saint Petersburg",
      "Novosibirsk",
      "Yekaterinburg",
      "Kazan",
      "Ufa",
    ],
  },
  {
    code: "ZA",
    name: "South Africa",
    ar: "جنوب أفريقيا",
    cities: [
      "Cape Town",
      "Johannesburg",
      "Durban",
      "Pretoria",
      "Port Elizabeth",
    ],
  },
  {
    code: "NG",
    name: "Nigeria",
    ar: "نيجيريا",
    cities: [
      "Lagos",
      "Kano",
      "Abuja",
      "Ibadan",
      "Kaduna",
      "Port Harcourt",
      "Maiduguri",
    ],
  },
  {
    code: "SN",
    name: "Senegal",
    ar: "السنغال",
    cities: ["Dakar", "Pikine", "Touba", "Thiès", "Kaolack"],
  },
  {
    code: "ML",
    name: "Mali",
    ar: "مالي",
    cities: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Gao"],
  },
  {
    code: "NE",
    name: "Niger",
    ar: "النيجر",
    cities: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua"],
  },
  {
    code: "MR",
    name: "Mauritania",
    ar: "موريتانيا",
    cities: ["Nouakchott", "Nouadhibou", "Néma", "Kaédi", "Rosso"],
  },
  {
    code: "SO",
    name: "Somalia",
    ar: "الصومال",
    cities: ["Mogadishu", "Hargeisa", "Bosaso", "Berbera", "Kismayo"],
  },
];
